### ISSUE TITLE
unity-ads-demo not show AD in non-test mode

### ISSUE THREAD

**Issue by koljanich** [wcoastsands/unity-ads-demo#2]
Hello! I use Unity 4.6.2f1, download unity-ads-demo and Unity ADS from Asset Store. Open the scene "JS-UnityAdsDemo". Check "Disable test mode" and put my ID, compile and push on Android device.
The 3 spheres in shadow and button "Waiting". Error Log:
02-14 12:50:52.412: E/UnityAds(31094): com.unity3d.ads.android.properties.UnityAdsProperties.isActivityDestroyed() (line:169) :: Couldn't get isDestroyed -method
02-14 12:50:52.879: E/NativeCrypto(31094): ssl=0x56552890 cert_verify_callback x509_store_ctx=0x5653da80 arg=0x0
02-14 12:50:52.880: E/NativeCrypto(31094): ssl=0x56552890 cert_verify_callback calling verifyCertificateChain authMethod=RSA
02-14 12:51:01.827: E/Trace(31169): error opening trace file: No such file or directory (2)
02-14 12:51:02.351: E/Trace(31199): error opening trace file: No such file or directory (2)
02-14 12:51:02.673: E/Trace(31217): error opening trace file: No such file or directory (2)
02-14 12:51:02.777: E/NativeCrypto(31169): ssl=0x4fe09dd0 cert_verify_callback x509_store_ctx=0x52d3eae8 arg=0x0
02-14 12:51:02.777: E/NativeCrypto(31169): ssl=0x4fe09dd0 cert_verify_callback calling verifyCertificateChain authMethod=RSA
02-14 12:51:03.159: E/CellLocation(31217): create GsmCellLocation
02-14 12:51:03.185: E/CellLocation(31217): create GsmCellLocation
02-14 12:51:03.256: E/CellLocation(31169): create GsmCellLocation
02-14 12:51:03.262: E/CellLocation(31169): create GsmCellLocation
02-14 12:51:11.820: E/Trace(31278): error opening trace file: No such file or directory (2)
02-14 12:51:30.544: E/OMXCodec(106): [OMX.MTK.AUDIO.DECODER.MP3] No more output data in fillOutputBuffer, mFilledBuffers size=0
02-14 12:51:30.554: E/OMXCodec(106): [OMX.MTK.AUDIO.DECODER.MP3] read() final return
02-14 12:51:30.701: E/DrmMtkUtil/DrmUtil(106): checkDcf: not dcf type, dcf version value [80]
02-14 12:51:30.702: E/DrmMtkUtil/DrmUtil(106): checkDcf: not dcf type, dcf version value [80]
02-14 12:51:30.704: E/DrmMtkUtil/DrmUtil(105): parseDcf: not dcf type, dcf version value [80]
02-14 12:51:30.704: E/DrmMtkPlugIn(105): onOpenDecryptSession() : failed to parse dcf file.
02-14 12:51:30.724: E/OMXCodec(106): [OMX.MTK.AUDIO.DECODER.MP3] No more output data in fillOutputBuffer, mFilledBuffers size=0
02-14 12:51:30.724: E/OMXCodec(106): [OMX.MTK.AUDIO.DECODER.MP3] read() final return
02-14 12:51:30.875: E/DrmMtkUtil/DrmUtil(106): checkDcf: not dcf type, dcf version value [80]
02-14 12:51:30.875: E/DrmMtkUtil/DrmUtil(106): checkDcf: not dcf type, dcf version value [80]
02-14 12:51:30.916: E/DrmMtkUtil/DrmUtil(106): checkDcf: not dcf type, dcf version value [80]
02-14 12:51:30.917: E/DrmMtkUtil/DrmUtil(106): checkDcf: not dcf type, dcf version value [80]

**Comment by wcoastsands** [comment]
Thanks for reporting. Could use some additional info, though. Would you mind rebuilding your app again with Development Mode enabled in Build Settings, and enable each of the debugging levels on the UnityAdsHelper component. You can leave Disable Test Mode checked to test live ads.

Before launching the app on your device, enter the following commands into the terminal:
```bash
clear 
adb logcat -c 
adb logcat -s Unity
```

Then run your app and copy the results of the logcat to a gist and post a link to it.

**Comment by wcoastsands** [comment]
Please update Unity Ads to the latest version available in the Asset Store and update Unity to the latest version, or [patch version if available](http://unity3d.com/unity/qa/patch-releases).
